### ISSUE TITLE
自己遇到的bug，不知道怎么解决

### ISSUE THREAD

**Issue by HouWan** [ibireme/YYImage#113]
```
==2223==AddressSanitizer's allocator is terminating the process instead of returning 0
==2223==If you don't like this behavior set allocator_may_return_null=1
==2223==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-902.0.39.1/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:218 "((0)) != (0)" (0x0, 0x0)
    #0 0x105717c7b in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x57c7b)
    #1 0x10572d297 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x6d297)
    #2 0x10571c4e7 in __sanitizer::ReportAllocatorCannotReturnNull() (/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x5c4e7)
    #3 0x10571c55f in __sanitizer::ReturnNullOrDieOnFailure::OnOOM() (/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x5c55f)
    #4 0x1056cce67 in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator32<__asan::AP32>, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<__asan::AP32> >, __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback, __sanitizer::ReturnNullOrDieOnFailure> >::Allocate(__sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<__asan::AP32> >*, unsigned long, unsigned long) (/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0xce67)
    #5 0x1056c8d93 in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) (/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x8d93)
    #6 0x1056c93d7 in __asan::asan_calloc(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*) (/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x93d7)
    #7 0x10570fbaf in __sanitizer_mz_calloc (/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x4fbaf)
    #8 0x1820ca02b in malloc_zone_calloc (/usr/lib/system/libsystem_malloc.dylib:arm64+0x402b)
    #9 0x1840abd5f in <redacted> (/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics:arm64+0x1f0d5f)
    #10 0x1840a2abf in <redacted> (/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics:arm64+0x1e7abf)
    #11 0x1840a1453 in <redacted> (/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics:arm64+0x1e6453)
    #12 0x183ebf44f in <redacted> (/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics:arm64+0x444f)
    #13 0x1840b5f6b in <redacted> (/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics:arm64+0x1faf6b)
    #14 0x1840a5df7 in CGContextDrawImageWithOptions (/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics:arm64+0x1eadf7)
    #15 0x1078eb33b in YYCGImageCreateDecodedCopy (/private/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/YYImage.framework/YYImage:arm64+0x2733b)
    #16 0x107901657 in -[YYImageDecoder _newUnblendedImageAtIndex:extendToCanvas:decoded:] (/private/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/YYImage.framework/YYImage:arm64+0x3d657)
    #17 0x1078f580b in -[YYImageDecoder _frameAtIndex:decodeForDisplay:] (/private/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/YYImage.framework/YYImage:arm64+0x3180b)
    #18 0x1078f404f in -[YYImageDecoder frameAtIndex:decodeForDisplay:] (/private/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/YYImage.framework/YYImage:arm64+0x3004f)
    #19 0x1078e6507 in -[YYImage initWithData:scale:] (/private/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/YYImage.framework/YYImage:arm64+0x22507)
    #20 0x107cf430b in __50-[YYWebImageOperation connectionDidFinishLoading:]_block_invoke (/private/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/YYWebImage.framework/YYWebImage:arm64+0x6430b)
    #21 0x10570dddb in __wrap_dispatch_async_block_invoke (/var/containers/Bundle/Application/CFFDF294-C5F0-4FE3-AEE1-5175D96E75D4/SunPigApp.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x4dddb)
    #22 0x107d4525f in _dispatch_call_block_and_release (/usr/lib/system/introspection/libdispatch.dylib:arm64+0x125f)
    #23 0x107d4521f in _dispatch_client_callout (/usr/lib/system/introspection/libdispatch.dylib:arm64+0x121f)
    #24 0x107d53e7f in _dispatch_queue_serial_drain (/usr/lib/system/introspection/libdispatch.dylib:arm64+0xfe7f)
    #25 0x107d4872f in _dispatch_queue_invoke (/usr/lib/system/introspection/libdispatch.dylib:arm64+0x472f)
    #26 0x107d54dd7 in _dispatch_root_queue_drain_deferred_wlh (/usr/lib/system/introspection/libdispatch.dylib:arm64+0x10dd7)
    #27 0x107d5bebb in _dispatch_workloop_worker_thread (/usr/lib/system/introspection/libdispatch.dylib:arm64+0x17ebb)
    #28 0x18222fe6f in _pthread_wqthread (/usr/lib/system/libsystem_pthread.dylib:arm64+0xe6f)
    #29 0x18222fb07 in start_wqthread (/usr/lib/system/libsystem_pthread.dylib:arm64+0xb07)
```

**Comment by HouWan** [comment]
出现的情景是：类似微博的页面，快速的往下翻页，会不定时出现这种情况而崩溃；

**Comment by fysteven** [comment]
把 Address Sanitizer 关掉再试试

**Comment by HouWan** [comment]
@fysteven 
Address Sanitizer 跟这个崩溃没关系，Address Sanitizer 只是捕获崩溃原因，后来我也没有找到原因，我估计是内存方面问题，比如野指针。因为一时半会解决不了，我去掉YYImage了，然后就不崩溃了。
https://www.jianshu.com/p/6b504428e16e
